version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: nest
    networks:
      - my-network

  nest-app:
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:secret123@localhost:5434/nest?schema=public
    depends_on:
      - dev-db
    networks:
      - my-network

networks:
  my-network: